#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("bcMapBC.Resource", IsApplication=true)]

namespace bcMapBC
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::bcMapBC.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::bcMapBC.Resource.String.Hello;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::bcMapBC.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::bcMapBC.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::bcMapBC.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bgimag = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int campus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int golide = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int justnje = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int monoandroidsplash = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int pic2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int pic2bandw = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sample_0 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sample_1 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sample_2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int sample_3 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int sample_4 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int sample_5 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int sample_6 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int sample_7 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int siteplan = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int testbandw = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int testcolour = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060017
			public const int Beta = 2131099671;
			
			// aapt resource value: 0x7f060013
			public const int COTTAGE = 2131099667;
			
			// aapt resource value: 0x7f06001d
			public const int Id_row = 2131099677;
			
			// aapt resource value: 0x7f06001f
			public const int LastName_row = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int Name_row = 2131099678;
			
			// aapt resource value: 0x7f06001c
			public const int Shmg = 2131099676;
			
			// aapt resource value: 0x7f060015
			public const int adminOffice = 2131099669;
			
			// aapt resource value: 0x7f06001b
			public const int alpha = 2131099675;
			
			// aapt resource value: 0x7f06000e
			public const int antwerp = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int brussels = 2131099665;
			
			// aapt resource value: 0x7f060006
			public const int button1 = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int caffeteria = 2131099660;
			
			// aapt resource value: 0x7f060020
			public const int contentFrame = 2131099680;
			
			// aapt resource value: 0x7f060012
			public const int delta = 2131099666;
			
			// aapt resource value: 0x7f060009
			public const int gama = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int genk = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int gridview = 2131099653;
			
			// aapt resource value: 0x7f06000f
			public const int hasselt = 2131099663;
			
			// aapt resource value: 0x7f060001
			public const int id = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int last = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int leuven = 2131099658;
			
			// aapt resource value: 0x7f060018
			public const int library = 2131099672;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout2 = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int listItems = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int name = 2131099650;
			
			// aapt resource value: 0x7f060019
			public const int omega = 2131099673;
			
			// aapt resource value: 0x7f06000d
			public const int parking = 2131099661;
			
			// aapt resource value: 0x7f060016
			public const int rep = 2131099670;
			
			// aapt resource value: 0x7f060000
			public const int shMsg = 2131099648;
			
			// aapt resource value: 0x7f06001a
			public const int sigma = 2131099674;
			
			// aapt resource value: 0x7f060010
			public const int theta = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int ypsilon = 2131099656;
			
			// aapt resource value: 0x7f060014
			public const int zetandthem = 2131099668;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int about = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int grid = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int record_view = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int zxingscanneractivitylayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int zxingscannerfragmentlayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int ApplicationName = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int Hello = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
